### ISSUE TITLE
Not ask any question about the audio setting

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10111]
Hi, I want to force all participants to allow automatically the microphone and not ask any question.

I mean that, if the moderator wants to force participants to mute -> OK, he/she mute all the participants.

Because in the middle of each session if the participants want to change its audio setting from listener to microphone, some few second must be wait until the synchronization is happens (about 3-10 second).

**Comment by simonschweizer** [comment]
You can do that by changing some settings in the `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` file:

```yaml
public:
  app:
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```
This will disable the listen only mode and will skip the echo test (to save the 3-10 seconds you mentioned).
