### ISSUE TITLE
Customize Screensharing Quality

### ISSUE THREAD

**Issue by tobka777** [bigbluebutton/bigbluebutton#10420]
We would like to improve the quality of screen sharings. Where is it possible to customize the bitrate of the sharing? 

In the config `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` there is `tias_main, as_main, tias_content, as_content` for VP8, but there is no documentation about these parameters and which others are possible. A significant increase of these values caused the screen to stall and not to improve the image.

By the way it would be helpful to explain the meaning of these parameters for H264 and VP8.
```
H264:
    profile_level_id: "42e01f"
    packetization_mode: "1"
    level_asymmetry_allowed: "1"
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
    max_mbps_main: "0"
    max_fs_main: "0"
    max_br_main: "0"
    max_mbps_content: "0"
    max_fs_content: "12288"
    max_br_content: "0"
VP8:
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
```
