### ISSUE TITLE
Elgato 4k60 Pro HDMI video aspect ratio and quality issues

### ISSUE THREAD

**Issue by wildeskraut** [bigbluebutton/bigbluebutton#10743]
**Describe the bug**
When using a Elgato 4k60 Pro as the Webcam video, the 4K video's aspect ratio is changed and the quality is reduced significant.
When using Elgato 4k60 Pro -> OBS virtual webcam -> BigBlueButton everything looks crips and fine.
So it has to be the direct communication Elgato 4k60 Pro -> BigBlueButton.
Other software as WebEx and Skype work fine picking up the video direclty from Elgato 4k60 Pro.

**To Reproduce**
1. Open a session, start webcam and see the bad result. Video is poor before sending it out.

**Expected behavior**
See a high quality video preview.

Picture how it actually looks like:
![BBB quality](https://user-images.githubusercontent.com/26325702/97487677-745f7d00-195d-11eb-835d-b5967a897591.png)

**Actual behavior**
How the video is expected to look:
![BBB direct good quality](https://user-images.githubusercontent.com/26325702/97487684-775a6d80-195d-11eb-99d4-119932ed0a76.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Chromium Edge

**Comment by eth3rgeist** [comment]
You could add a profile for 16:9 sources:

`/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

`cameraProfiles` entry:

```yaml
    - id: hd169
      name: For emergency use only
      default: false
      bitrate: 800
      constraints:
        width:
          min: 640
          ideal: 1920
        height:
          min: 400
          ideal: 1080
        aspectRatio:
          ideal: 1.7777777778
```

After a server reload you should be able to select a profile named `For emergency use only` which presents you with 16:9 video. Tune the settings to your liking.
