### ISSUE TITLE
bbb-html5: `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` not writable

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#10924]
bbb-html5 2.2.0-1095 contains a read only settings file.

    $ ls -lh /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    -r--r--r-- 1 meteor meteor 13K Nov 28 17:14 /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    $ dpkg -S /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    bbb-html5: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Comment by erisd** [comment]
We solved that with an additional ansible task - the feedback to some security related problems was - until now - not so impressive...
```
- name: fix bbb-html5 app permissions
  file:
    path: /usr/share/meteor/bundle
    state: directory
    recurse: true
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
```
... have you seen the permissions in /etc/systemd/system and /usr/lib/systemd/system ?
