### ISSUE TITLE
Change whiteboard default colors to colorblind safe values to improve accessibility

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#11548]
**Is your feature request related to a problem? Please describe.**
Currently, BBB uses base colors (#00FF00, #00FFFF, etc.) by default for the whiteboard. It might be nice to select a more color-blind safe set as default for whiteboard colors.

**Describe the solution you'd like**
Change the default whiteboard colors to a tested color-blind safe set, e.g., from https://personal.sron.nl/~pault/data/colourschemes.pdf

**Additional context**
This is an accessibility quick-win.

**Comment by antobinary** [comment]
Thank you for this suggestion!

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/11570#pullrequestreview-608260850
from @basisbit: 

> These colors are all rather dark and of the same "darkness". The color choice isn't really usable for drawing, but instead is only somewhat usable for marking areas. It does not even contain white / black and changes the amounts of selectable colors from 10 to 5. All in all, this is a severe reduction in usability of the whiteboard for many use cases. I'd suggest not merging this PR in its current state.

@tylercopeland and @ichdasich, Let's discuss here if any change is to be made, obtain support from other members too and only then proceed with implementation.

We tried to follow the guide linked in the description, first with muted colors, then with vibrant, and no consensus was reached. For now we'll stick to the pallette we have unless all are in agreement.

**Comment by ichdasich** [comment]
So, i already made this change on my infra. And i did not go for that extreme of a change. However, colorblind colleagues noted that this already improved color distinguishability (a bit). 

New colors:
![Colors_new](https://user-images.githubusercontent.com/5586936/110692065-3bc29080-81e6-11eb-81b2-62baad683fff.PNG)


Old Colors:
![Colors_old](https://user-images.githubusercontent.com/5586936/110692083-411fdb00-81e6-11eb-8049-c4392095c1d7.PNG)

```
    toolbar:
      multiUserPenOnly: false
      colors:
      - label: black
        value: "#000000"
      - label: white
        value: "#ffffff"
      - label: red
        value: "#dc050c"
      - label: orange
        value: "#f1932d"
      - label: eletricLime
        value: "#f6f056"
      - label: Lime
        value: "#4eb265"
      - label: Cyan
        value: "#7bafde"
      - label: dodgerBlue
        value: "#5289c7"
      - label: blue
        value: "#1965b0"
      - label: violet
        value: "#882e72"
      - label: magenta
        value: "#ae76a3"
      - label: silver
        value: "#777777"
```
