### ISSUE TITLE
audio: rewrite the HTML5 client bridge configuration scheme

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#13267]
**Is your feature request related to a problem? Please describe.**

We have a quasi-extensible media bridge system for audio. The bridge interface stuff is in place, but the way we configure them is suboptimal. There's a flag called useKurento which enables the listen only bridge and that's it.

We should be able to configure that in a more declarative and flexible way. One that allows us to add additional bridges and say what they're responsible for (full audio, listen only).

Rationale: make it easier to transparently switch bridges.
Needed for: new webrtc-sfu (or modified SIP) signaling.

**Describe the solution you'd like**
1. Add a new configuration set to define which bridge to use:
```
     defaultFullAudioBridge: $DEFAULT_BRIDGE1
     defaultListenOnlyBridge: $DEFAULT_BRIDGE2
     fullAudio: $BRIDGE1_NAME
     listenOnly: $BRIDGE2_NAME
```
2. Add a new configuration array to define which are the implemented bridges:
```
    audioBridges:
      - name: $BRIDGE_NAME1
        path: $/path/to/bridge1 # as in path of the import statement
      - name: $BRIDGE_NAME2
        path: $/path/to/bridge2 # as in path of the import statement
      [...]
```
3. Add a bridge storage which reads up the bridges in 2, sanitizes, validate and load them up.
  - The bridge storage should be used by audio-manager
  - The bridge storage should keep bridge specific logic transparent
  - audio-manager reads the configurations in 1, asks the registrar for the bridges. If anything is wrong, fall back to the default ones.

**Additional context**

Rationale about the `audioBridge` config `path` prop:
  - Making it a configurable path allows a few clever things:
    * Adding bridges without needing to manually aggregate them in an index.js of sorts or read the file system up.
    * Drop-in bridges: 3rd parties can drop bridges to the /public/compatibility without having to rebuild packags
    * Bridges as modules: path can be used as a module name as well, as long as it is in package.json
