### ISSUE TITLE
Screenshare: add a client bridge configuration system

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#13269]
**Is your feature request related to a problem? Please describe.**

The screen share module in the client currently has a partially implemented bridge system.
It has just one bridge, and it isn't configurable.
We should be able to configure that in a declarative and flexible way. One that allows us to add additional bridges.

Rationale: make it easier to transparently switch screen sharing bridges.
Motivation: invasive changes while preserving functionality; extensibility.

**Describe the solution you'd like**

A bridge's roles for screen sharing should be:
  - Handle WebRTC stack code
  - Handle signaling code
  
High level steps to do this:

1. Add a new configuration set to define which bridge to use:
```
     screenshareDefaultBridge: $DEFAULT_BRIDGE1
     screenshareBridge: $BRIDGE2_NAME
```

2. Add a new configuration array to define which are the implemented bridges:
```
    screenshareBridges:
      - name: $BRIDGE_NAME1
        path: $/path/to/bridge1 # as in path of the import statement
      - name: $BRIDGE_NAME2
        path: $/path/to/bridge2 # as in path of the import statement
      [...]
```
3. Add a bridge storage which reads up the bridges in 2, sanitizes, validate and load them up.
  - The bridge storage should be used by a new screenshare aggregator service (call it screenshare-bridges)
  - The bridge storage should keep bridge specific logic transparent
  - screenshare-bridges reads the configurations in 1, asks the registrar for the bridges. If anything is wrong, fall back to the default ones.
  
**Additional information**

Related: #13267 https://github.com/bigbluebutton/bigbluebutton/issues/13270
