### ISSUE TITLE
Webcams: add a client bridge configuration system

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#13270]
**Is your feature request related to a problem? Please describe.**

video-provider doesn't even have a hint of what a configurable bridge looks like.
We should be able to configure that in a declarative and flexible way. One that allows us to add additional bridges.

Rationale: make it easier to transparently switch bridges.
Motivation: invasive changes while preserving functionality; extensibility.

**Describe the solution you'd like**

A bridge's roles in video-provider should be:
  - Handle WebRTC stack code
  - Handle signaling code
  
High level steps to do this:

1. Add a new configuration set to define which bridge to use:
```
     videoProviderDefaultBridge: $DEFAULT_BRIDGE1
     videoProviderBridge: $BRIDGE2_NAME
```

2. Add a new configuration array to define which are the implemented bridges:
```
    videoProviderBridges:
      - name: $BRIDGE_NAME1
        path: $/path/to/bridge1 # as in path of the import statement
      - name: $BRIDGE_NAME2
        path: $/path/to/bridge2 # as in path of the import statement
      [...]
```
3. Add a bridge storage which reads up the bridges in 2, sanitizes, validate and load them up.
  - The bridge storage should be used by a new video-provider aggregator service (call it video-bridges)
  - The bridge storage should keep bridge specific logic transparent
  - video-bridges reads the configurations in 1, asks the registrar for the bridges. If anything is wrong, fall back to the default ones.

**Additional context**

Related: https://github.com/bigbluebutton/bigbluebutton/issues/13267 https://github.com/bigbluebutton/bigbluebutton/issues/13269
Depends on: #12954
