### ISSUE TITLE
bbb-html5 configuration override file merges arrays instead of replaces

### ISSUE THREAD

**Issue by mabeyj** [bigbluebutton/bigbluebutton#13597]
**Describe the bug**
Arrays in bbb-html5's configuration override file (`/etc/bigbluebutton/bbb-html5.yml`) are merged with the default settings rather than replaced. This doesn't allow for removing values from arrays using the override file. For example, removing a webcam profile. In these cases, the default configuration file still needs to be edited.

**To Reproduce**
As a simple example, using the override file to remove all webcam profiles except for one:

```yaml
public:
  kurento:
    cameraProfiles:
      - id: medium
        name: Medium
        default: true
        bitrate: 100
```

1. Edit ``/etc/bigbluebutton/bbb-html5.yml`` and set its contents to the above
2. Restart BBB
3. Start a meeting
4. Check the quality options when sharing a webcam

**Expected behavior**
Arrays are replaced. The override file sets one profile, so there should only be the one profile available in BBB.

**Actual behavior**
Arrays are merged. The default webcam profiles not present in the override file (low, high, HD) still exist and are not removed.

**BBB version:**
BigBlueButton Server 2.3.15 (2495)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 95

**Comment by olwe0002** [comment]
additional info: also the merge does not work as expected. lets assume this setting in `/etc/bigbluebutton/bbb-html5.yml`

```
public:
  kurento:
    cameraProfiles:
    - bitrate: 100
      default: true
      id: low
      name: Low
    - bitrate: 200
      default: false
      id: medium
      name: Medium
```

in the default `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`  the `medium` entry has the `default: true` enabled. With the override above, nothing happens. The `medium` setting is still the default one, even that the `low` setting is set as default.

but to open this discussion, in my opinion  the merge instead of replace is not this wrong, as you don't have to explicitly defined all elements again which are not changed.
