### ISSUE TITLE
bbb-html5 configuration override file only overrides existing variables

### ISSUE THREAD

**Issue by Poerty1** [bigbluebutton/bigbluebutton#13729]
**Describe the bug**
Variables in bbb-html5's configuration override file (/etc/bigbluebutton/bbb-html5.yml) are not set, if the variables do not exist in the meteor's configuration file (/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml). For example I'm using the following override file:

```
public:
  app:
    mirrorOwnWebcam: false
    viewersInWebcam: 30
    defaultSettings:
      application:
        microphoneConstraints:
          autoGainControl:
            ideal: false
          echoCancellation:
            ideal: true
          noiseSuppression:
            ideal: false
  chat:
    startClosed: true
  layout:
    showParticipantsOnLogin: false
```

I get set `mirrorOwnWebcam`, `viewersInWebcam`, `startClosed` and `showParticipantsOnLogin`. Not set are `autoGainControl`, `echoCancellation` and `noiseSuppression`.
I guess, it's because in the original meteor's configuration file the microphoneConstraints are not set but behind a comment.
It is possible to deactivate the `audio filters for the microphone` during the session, which I want to have as an default setting.

**To Reproduce**
To check autoGainControl, I use live music with dynamic loudness (organ).

**Expected behavior**
All variables in bbb-html5's configuration override file are effective, even if there is no inital default value set.

**Actual behavior**
Only variables in bbb-html5's configuration override file are set, the exist in the default settings.

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: Windows 10 and Ubuntu 20
 - Browser: Vivaldi, Chrome, Opera
 - Version: actual
