### ISSUE TITLE
bbb-webrtc-sfu with mediasoup tries to attach to freeswitch on wrong IP

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#14394]
**Describe the bug**
In a cluster running BBB 2.4.4, we noticed an increase in the output of our firewall (around the time of the upgrade from 2.4.2 to 2.4.4), tracing it back to our BBB nodes. The log looks like this:

```
<timestamp> <nodename> kernel: IN= OUT=eth0 SRC=<nodeip> DST=10.0.3.66 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=909 DF PROTO=TCP SPT=43160 DPT=5066 WINDOW=64240 RES=0x00 SYN URGP=0
```
and the entries appear at a rapid interval. This is understandable, because `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` has:

```yaml
freeswitch:
  ip: 10.0.3.66
  sip_ip: 10.0.3.66
  port: 5066
```
However, we do not enable full audio. Here is the contents of `/etc/bigbluebutton/bbb-webrtc-sfu/production.yml`:

```yaml
balancing-strategy: ROUND_ROBIN
videoMediaServer: mediasoup
screenshareMediaServer: mediasoup
audioMediaServer: mediasoup
listenOnlyMediaServer: mediasoup
localIpAddress: <ipv4>
mediasoup:
  webrtc:
    listenIps:
    - ip: 0.0.0.0
      announcedIp: <ipv4>
    - ip: '::'
      announcedIp: <ipv6>
  plainRtp:
    listenIps:
    - ip: 0.0.0.0
      announcedIp: <ipv4>
    - ip: '::'
      announcedIp: <ipv6>
kurento:
- ip: <ipv4>
  url: ws://127.0.0.1:8888/kurento
  mediaType: main
  ipClassMappings:
    local: ''
    private: ''
    public: ''
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
freeswitch:
  esl_password: <esl_password>
log:
  level: warn
  filename: null
```
I wonder if this means that mediasoup is trying to use part of its fullaudio capabilities, although it shouldn't?

I will change the filename to `/dev/stdout` and monitor the situation over the next days through the journal log. I would like to avoid to push the log level to debug in prod though.

**Extra Information**

Setup has only public IP addresses (dual-stacked).

**Expected behavior**
No attempt to connect to freeswitch at default IP

**Actual behavior**
Attempt to connect to freeswitch at the default IP
