### ISSUE TITLE
Firefox for Android webcam aspect ratio problem

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#14476]
**Describe the bug**
Depending on the camera profile and the orientation of the device, the the webcam image is very wide/high.

**To Reproduce**
Share a webcam in Firefox for Android. It looks okay when the quality is low. If you use the profile "high" or "high definition" the aspect ratio is wrong.

Reproducible on `test24.bigbluebutton.org`.

**Expected behavior**
The webcam should probably be either `4x3` or `16x9`? Not sure if it should be dependent on the orientation of the device.

**Screenshots**

![Screenshot from 2022-02-28 16-41-27](https://user-images.githubusercontent.com/16013327/156012503-4b39de7a-dfc2-4d3e-9fd2-217ab2ea7e0f.png)
![Screenshot from 2022-02-28 16-41-09](https://user-images.githubusercontent.com/16013327/156012509-85c22ec2-1867-4244-aa99-93e5917a9c2a.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3 (FP3)
 - OS: Android 10
 - Browser: Firefox for Android, Fennec 97.1.1 (latest from f-droid)

**Additional context**
I can't explain why it only happens in high quality camera profiles. On my `2.4.4`-server it works fine with "Low" but breaks with "High".
```
      - id: low
        name: Low
        default: true
        bitrate: 100
      - id: high
        name: High
        default: false
        bitrate: 800
        constraints:
          width: 1280
          frameRate: 15
```
