### ISSUE TITLE
Update whiteboard.toolbar settings.yml to support tldraw (part 1)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16168]
**Describe the bug**
As of BBB 2.6.0-beta.3 we still carry the old (pre-tldraw) settings for the whiteboard toolbars:

```
public:
  whiteboard:
    annotationsQueueProcessInterval: 60
    cursorInterval: 150
    maxStickyNoteLength: 1000
    annotations:
      status:
        start: DRAW_START
        update: DRAW_UPDATE
        end: DRAW_END
    toolbar:
      multiUserPenOnly: false
      colors:
        - label: black
          value: '#000000'
        - label: white
          value: '#ffffff'
        - label: red
          value: '#ff0000'
        - label: orange
          value: '#ff8800'
        - label: eletricLime
          value: '#ccff00'
        - label: Lime
          value: '#00ff00'
        - label: Cyan
          value: '#00ffff'
        - label: dodgerBlue
          value: '#0088ff'
        - label: blue
          value: '#0000ff'
        - label: violet
          value: '#8800ff'
        - label: magenta
          value: '#ff00ff'
        - label: silver
          value: '#c0c0c0'
      thickness:
        - value: 14
        - value: 12
        - value: 10
        - value: 8
        - value: 6
        - value: 4
        - value: 2
        - value: 1
      font_sizes:
        - value: 36
        - value: 32
        - value: 28
        - value: 24
        - value: 20
        - value: 16
      tools:
        - icon: text_tool
          value: text
        - icon: line_tool
          value: line
        - icon: circle_tool
          value: ellipse
        - icon: triangle_tool
          value: triangle
        - icon: rectangle_tool
          value: rectangle
        - icon: pen_tool
          value: pencil
        - icon: hand
          value: hand
      presenterTools:
        - text
        - line
        - ellipse
        - triangle
        - rectangle
        - pencil
        - hand
      multiUserTools:
        - text
        - line
        - ellipse
        - triangle
        - rectangle
        - pencil
```

Most of these are obsolete if not all.
- [ ] We should chat about which configs we no longer need (and remove them)
- [ ] ensure `maxStickyNoteLength` is still functional
- [ ] open separate issues about items we need to re-implement, for example - configurable preventing viewers from using sticky notes, reimplement `multiUserPenOnly`, ...
