### ISSUE TITLE
fullaudio in multiple conferences in parallel on firefox not possible anymore

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#16426]
**Describe the bug**
If you joined a BBB conference with microphone in one firefox tab and try to join another conference in a different tab, you can not anymore connect with the microphone but only listen only.

**To Reproduce**
- join a conference in one tab with full audio (microphone) .
- join another conference in another tab and try to connect with microphone.
- after some time trying, BBB returns error 1005.

**Expected behavior**
You should be able to connect microphone in multiple sessions/tabs.

**Actual behavior**
Only one connection is possible. If you disconnect microphone in the first conference, you can connect in the second one.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox-ESR 102.6

It used to be possible until version 2.5.8 . 2.5.9, 10 and 11 have the problem.
2.6.0-beta.4 also has the problem. I did not test with other 2.6 versions.
fullaudiobridge is set to default (sipjs)
If I change it to fullaudio the problem goes away.

**Comment by ffdixon** [comment]
>  I did not test with other 2.6 versions. fullaudiobridge is set to default (sipjs)

Can you test on 

 https://test26.bigbluebutton.org/

and let us know if the problem exists there as well.  I just did a test and can see that it's joining with fullaudio.  Opening a new tab in FireFox and going to `about:webrtc` shows mediasoup as the client for audio

```
Remote SDP (Answer)

v=0
o=mediasoup-client 10000 1 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-512 4F:54:DD:DE:2D:41:9D:D4:58:26:2C:92:77:43:71:63:78:4F:5E:0C:E9:6A:00:2B:50:A8:F0:FD:18:38:52:28:B3:D3:11:43:86:27:90:8D:C5:79:14:8D:4A:7C:C1:E1:79:98:29:8F:37:E6:D3:ED:CE:3B:EB:12:FD:DD:88:56
...
```

**Comment by christmart** [comment]
Is test26.bigbluebutton.org with 
```
  media:
    audio:
      defaultFullAudioBridge: fullaudio
```
or with sipjs? It happens with sipjs.

**Comment by christmart** [comment]
I get the same error on test26, if I have a running mic connection in my normal 2.5.8 conference.

**Comment by ffdixon** [comment]
Here's the `/etc/bigbluebutton/bbb-html5.yml` configuration for dev26.bigbluebutton.org

```
public:
  media:
    sipjsHackViaWs: true
    traceSip: true
    audio:
      defaultFullAudioBridge: fullaudio
    showVolumeMeter: true
    localEchoTest:
      enabled: true
      initialHearingState: true
      useRtcLoopbackInChromium: true
    # networkPriorities: DSCP markings for each media type. Chromium only, applies
    # to sender flows. See https://datatracker.ietf.org/doc/html/rfc8837#section-5
    # for further info.
    networkPriorities:
      audio: high
      webcam: medium
      screenshare: medium
  kurento:
    signalCandidates: false
    pagination:
      desktopPageSizes:
        moderator: 0
        viewer: 0
    mobilePageSizes:
      moderator: 0
      viewer: 0
  chat:
    enableEmojiPicker: true
  app:
    audioCaptions:
      enabled: true
```
