### ISSUE TITLE
Broken documentation for "single video file"

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#17504]
As written here:
https://docs.bigbluebutton.org/administration/customize/#install-additional-recording-processing-formats

A lot of this is written in single quotes, but in the corresponding files we have double quotes.
Also there is no /usr/local/bigbluebutton/core/scripts/video.yml or /usr/local/bigbluebutton/core/scripts/screenshare.yml

This really needs to have some clarification.

**Comment by GuiLeme** [comment]
Hello, @lonesomewalker.

I just made a PR to insert some new information on the recording part of the docs: https://github.com/bigbluebutton/bigbluebutton/pull/17865. Also, in that PR I fixed the `deploy.sh` to work for other formats as well (in case you use that script).

>  A lot of this is written in single quotes, but in the corresponding files we have double quotes.

Thank you for the concern, so, as far as I know double or single quotes will not be taken into account when the ruby scripts are running, they are simply strings. But I also tested mixing both approaches (single and double quotes in the same file, for different parameters) and it worked just fine, for example:

```yml
steps:
  archive: "sanity"
  sanity: "captions"
  captions: 
    - 'process:presentation'
    - "process:video"
  "process:presentation": 'publish:presentation'  # <-- Single quotes
  "process:video": "publish:video"
```

But again, thank you for pointing that out!

> Also there is no /usr/local/bigbluebutton/core/scripts/video.yml or /usr/local/bigbluebutton/core/scripts/screenshare.yml

Hum, do you have video or sceenshare packages installed? Because those files don't come as default when installing BBB, as far as I know. To see that, please check the `/usr/local/bigbluebutton/core/scripts/process` and `/usr/local/bigbluebutton/core/scripts/process` directories, there must have the `.rb` files for each format, e.g.: `video.rb`. If there is only `presentation.rb`, chances are that those formats are not installed.
