### ISSUE TITLE
Live caption docs.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#17785]
![livecaption](https://user-images.githubusercontent.com/519542/235690660-2e61c613-0c25-4054-b721-fa87a7bc8c8d.jpg)

Notice the missing image,  and the  ... in the settings.yml lines.

**Comment by hiroshisuga** [comment]
The three dots implicate the presence of other setting items. So I didn't change. 
It is true, on the other hand, that users may simply copy and paste this setting including the three dots and suffer an error because it reads 'add the following'.
One possibility:
```
public:
  app:
  # you may have other settings here
    audioCaptions:
      enabled: true
```
