### ISSUE TITLE
Update documentation to prefer IPv6 over IPv4 WebRTC candidates

### ISSUE THREAD

**Issue by SoerenBusse** [bigbluebutton/bigbluebutton#20966]
**Link to the portion of the docs that is out of date**
https://docs.bigbluebutton.org/support/troubleshooting/#configure-mediasoup-to-use-ipv6
https://docs.bigbluebutton.org/administration/firewall-configuration/#updating-mediasoup

**Describe what you believe the correct version should be**
The documentation recommends adding the IPv6 address to the YAML-array in `production.yml` after the IPv4 address:
```
mediasoup:
  webrtc:
    listenIps:
      - ip: 0.0.0.0
        announcedIp: 192.0.2.0
      - ip: 2001:db8::
```

This means that BigBlueButton (mediasoup) offers the IPv4 candidate with a higher priority than IPv6. Depending on the client's network (e.g. mobile IPv6 only networks with 464XLAT), this may lead to the use of "workaround protocols" such as STUN/TURN, even though a public IPv6 address is available to the host.

![v4](https://github.com/user-attachments/assets/5163a726-9f8c-448c-8d58-4c3bb6f7bfae)

The recommended configuration should be to add the IPv6 address before the IPv4 address, to give priority to IPv6 connectivity:
```
mediasoup:
  webrtc:
    listenIps:
      - ip: 2001:db8::
      - ip: 0.0.0.0
        announcedIp: 192.0.2.0
```

Now the IPv6 candidate has a higher priority and the WebRTC channel is established via IPv6.

![v6](https://github.com/user-attachments/assets/56131b88-dd14-4ae7-9679-49915cc18063)
