### ISSUE TITLE
askForFeedbackOnLogout set to false but the window shows up

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#21282]
**Describe the bug**

**To Reproduce**
Configure bbb-html.yml to have the following this

```yaml
public:
  app:
    askForFeedbackOnLogout: false
```

1. End a meeting with the configuration above.

**Expected behavior**
Should not see the ask for feedback window.

**Actual behavior**
The ask for feedback window shows up.

**BBB version:**
BigBlueButton Server 2.7.12 (The issue is present in previous 2.7.x)
