### ISSUE TITLE
whiteboardToolbarAutoHide seems not to take effect

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/bigbluebutton#21686]
**Describe the bug**
Enabling

```
public:
  app:
    defaultSettings:
      application:
        whiteboardToolbarAutoHide: true
```

for `/etc/bigbluebutton/bbb-html5.yml` does not seem to have effect

**Expected behavior**
Hide Whiteboard Toolbars from start on.

**Actual behavior**
Whiteboard Toolbars  remains visible.

**BBB version:**
BigBlueButton Server 3.0.0-beta.4 & 3.0.0-beta.5 (Client build: 875)

**Desktop:**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [132]
