### ISSUE TITLE
[3.0.0-beta6] speech-to-text option when joining audio not showing up

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/bigbluebutton#21805]
**Describe the bug**
Hello one and all.

Just configured BBB 3.0b6 as written here -> https://docs.bigbluebutton.org/administration/customize/#configuration-of-gladiaio

bbb-transcription-controller is running fine. Gladia proxy is listing on 8777. So I would expect the speech-to-text option to show. 

What else could I check? Same settings work flawless with Version 2.7.15.

cheers!

**To Reproduce**
1. Configure audioCaptions.enabled true and audioCaptions.provider.gladia + everything else needed
2. restart bigbluebutton
3. start meeting
4. no speech-to-text-option in joining audio dialog

**Expected behavior**
speech-to-text-option in audio dialog visible

**Actual behavior**
no speec-to-text-option

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox, Chrome 131
 - Version 3.0.0-beta6

**Comment by himpierre** [comment]
Same problem with beta7. Am I the only one with this problem?
cheers!

**Comment by lfzawacki** [comment]
It could be a regression in the newest 3.0 codebase. I'll look into it later today.

**Comment by lfzawacki** [comment]
I just tested it with v3.0.0-beta.7 and the latest bbb-transcription-controller. It seems to be working, be sure to select the language on the audio modal and the same one in the CC button.

If you're not seeing the language selector maybe the html5 options were not set in `/etc/bigbluebutton/bbb-html5.yml`. Here's an excerpt of what I have there:

```
app:
  audioCaptions:
    enabled: true
    alwaysVisible: true
    ...
    provider: gladia
```

Here's what I have in `/usr/local/bigbluebutton/bbb-transcription-controller/config/default.yml`:

```
gladia:
  startMessage: '{"x_gladia_key": "YOUR KEY HERE", "sample_rate": 0, "bit_depth": 16, "model_type": "fast", "endpointing": 20 }'
  endMessage: '{}'
  server: ws://localhost:8777
  hint: ''
  proxy:
    enabled: true
    address: "wss://api.gladia.io/audio/text/audio-transcription"
    minPartialDuration: 3
    languageManual: true
```

**Comment by himpierre** [comment]
Thanks for your answer! The switch "always visible" was new to me. Had high hopes this would fix my issue. But sadly it didn't.

Is there something I can do to debug this a little bit more? 

cheers! t.

Am 19. Dezember 2024 21:58:19 MEZ schrieb Lucas ***@***.***>:
>I just tested it with v3.0.0-beta.7 and the latest bbb-transcription-controller. It seems to be working, be sure to select the language on the audio modal and the same one in the CC button.
>
>If you're not seeing the language selector maybe the html5 options were not set in `/etc/bigbluebutton/bbb-html5.yml`. Here's an excerpt of what I have there:
>
>```
>app:
>  audioCaptions:
>    enabled: true
>    alwaysVisible: true
>    ...
>    provider: gladia
>```
>
>Here's what I have in `/usr/local/bigbluebutton/bbb-transcription-controller/config/default.yml`:
>
>```
>gladia:
>  startMessage: '{"x_gladia_key": "YOUR KEY HERE", "sample_rate": 0, "bit_depth": 16, "model_type": "fast", "endpointing": 20 }'
>  endMessage: '{}'
>  server: ws://localhost:8777
>  hint: ''
>  proxy:
>    enabled: true
>    address: "wss://api.gladia.io/audio/text/audio-transcription"
>    minPartialDuration: 3
>    languageManual: true
>```
>

**Comment by lfzawacki** [comment]
You can check the running status with:

    sudo systemctl status bbb-transcription-controller

Check for errors in the logs in `/var/log/bigbluebutton/bbb-transcription-controller.log` and `/var/log/bigbluebutton/gladia-proxy.log`

What happened to me before was that I setup invalid log paths in  `/usr/local/bigbluebutton/bbb-transcription-controller/config/default.yml` . This caused the application service to not start. Here's the first lines of my config file:

```
log:
  filename: /var/log/bigbluebutton/bbb-transcription-controller.log
  level: debug
  stdout: true
  gladiaProxy: /var/log/bigbluebutton/gladia-proxy.log
```
