### ISSUE TITLE
[3.0] Breakout defaults from bbb-html5.yml not respected

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#21950]
Just did a fresh install of beta ~6~ (oops edit) 7. In my /etc/bigbluebutton/bbb-html5.yml, I have:

```
public:
  ...
  app:
    breakouts:
      captureWhiteboardByDefault: true
      captureSharedNotesByDefault: true
      sendInvitationToAssignedModeratorsByDefault: true

```

These default settings do not seem to apply in the new breakout rooms dialog. (Working as expected in my production 2.7)
