### ISSUE TITLE
High compute load when audio modal open and captions enabled

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#22078]
**Describe the bug**
When the join audio dialog is open (on page load), the client is consuming lots of CPU (a full core in my case).
It only seems to happen if automatic captions are enabled.

```
# cat /etc/bigbluebutton/bbb-html5.yml 
public:
  app:
    audioCaptions:
      enabled: true
      language:
        available:
          - en-US
          - es-ES
          - fr-FR
          - pt-BR
```

**To Reproduce**
1. Start a session and join it
2. [Grant access to the microphone but don't join audio yet]

**Expected behavior**
Minimal CPU load for just staying on the page, single user, nothing in the background.

**Actual behavior**
Something is going on in the background which is causing heavy load in the client.

**Screenshots**

![Image](https://github.com/user-attachments/assets/3a8d2429-88df-4138-9730-c9c0af48ad18)

**BBB version:**
BigBlueButton 3.0.0-rc.1
