### ISSUE TITLE
Customizing the list of whiteboard tools

### ISSUE THREAD

**Issue by g-v-egidy** [bigbluebutton/bigbluebutton#23365]
**Describe the bug**
Limiting/Customizing of the available whiteboard tools via settings.yml or `clientSettingsOverride` does not work. I would like to remove some tools that are unnecessary for my usecase to make it faster to use. The full amount of available tools means the presenter has to search for the right tool.

**To Reproduce**
1. Edit `/usr/share/bigbluebutton/html5-client/private/config/settings.yml`
2. Configure the whiteboard like this:
```
public:
  whiteboard:
    toolbar:
      presenterTools:
        - select
        - hand
        - draw
        - arrow
        - text
        - rectangle
        - delete-selected-items
        - highlight
        - cloud
        - line
``` 
4. Reboot the server to be really sure the new content is loaded
5. Open a new session

I explicitly modified settings.yml here, to be sure that the config merging isn't causing this.

**Expected behavior**
Only the tools listed above appear in the whiteboard toolbar

**Actual behavior**
All tools are shown in the whiteboard toolbar.

**Screenshots**
![Image](https://github.com/user-attachments/assets/c90991ea-abe4-48ad-9903-c042c3fafbe1)

**BBB version:**
BigBlueButton Server 3.0.8 (2609)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 139.0
