### ISSUE TITLE
Update the base font size on desktop to 14px

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6335]

**Comment by antobinary** [comment]
We currently have these 2 settings:
In typography.scss:
```
   --font-size-base: 1rem;
  --font-size-large: 1.25rem;
  --font-size-small: 0.875rem;
```

And in settings.yml
```
    defaultSettings:
      application:
        (...)
        fontSize: 16px
```
So please clarify - do you want us to scale all down as in
base = 14px
large = 16px
small = 12px kind of thing?
