### ISSUE TITLE
Audio broken after changing the IP address of a BigBlueButton machine

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6901]
When an IP address of a BigBlueButton machine is changed, the audio is broken. It happens as example when using DigitalOcean snapshot to create a droplet on the fly. I had to manually re-configure the following files to make audio work again.

File `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`
```yaml
kurento:
- ip: 138.68.38.255
  url: ws://138.68.38.255:8888/kurento
...
localIpAddress: 138.68.38.255
...
freeswitch:
  ip: 138.68.38.255
```

File `/etc/bigbluebutton/nginx/sip.nginx`
```
proxy_pass https://138.68.38.255:7443;
```

File `/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties`
```properties
    # The ip and port the BBB SIP app is going to use
    bbb.sip.app.ip=138.68.38.255

    # The ip and port of the FreeSWITCH server
    freeswitch.ip=138.68.38.255
```

File `/opt/freeswitch/etc/freeswitch/vars.xml` (Set `local_ip_v4` to **auto**)
```xml
<X-PRE-PROCESS cmd="set" data="local_ip_v4=auto"/>
```

There is currently now way to do this using `bbb-conf`. We need a command to automate this, we also need a warning in `bbb-conf --check`
