### ISSUE TITLE
Screen sharing from lower bandwidth users slow, low video quality

### ISSUE THREAD

**Issue by rcitdept** [bigbluebutton/bigbluebutton#7881]
We're really enjoying BigBlueButton so far, thank you for all the hard work creating this project.

The main feature we are utilizing is the screen sharing. One thing we've noticed is that users with slower upload speeds are having difficulty sharing their screens. The users in question both have a 1mbps upload speed. When sharing their screen, the text is grainy and updates are very slow to see on the remote end. Are there any recommended tweaks for Kurento or another BBB component that will allow lower bandwidth users to share their screens with better quality and without using their whole upload speed?

I see in the `conference-media-specs` section of the Kurento config a speed of 1.5mbps 'tias_content'. Does this mean that anyone sharing their screen would need to have at least 1.5mbps of upload speed to share without slowdowns or quality drops?

Below are the current contents of our `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` file.

```
kurento:
- ip: <ip>
  url: ws://<hostname>:8888/kurento
video-transposing-ceiling: 50
audio-transposing-ceiling: 100
localIpAddress: <ip>
acceptSelfSignedCertificate: false
redisHost: 127.0.0.1
redisPort: "6379"
clientPort: "3008"
minVideoPort: 30000
maxVideoPort: 33000
mediaFlowTimeoutDuration: 15000
from-screenshare: from-screenshare-sfu
to-screenshare: to-screenshare-sfu
from-video: from-video-sfu
to-video: to-video-sfu
from-audio: from-audio-sfu
to-audio: to-audio-sfu
to-akka: to-akka-apps-redis-channel
from-akka: from-akka-apps-redis-channel
to-stream: to-sfu-redis-channel
from-stream: from-stream-sfu
to-html5: to-html5-redis-channel
common-message-version: 2.x
screenshareKeyframeInterval: 0
screenshareEnableFlashRTPBridge: false
recordScreenSharing: true
recordWebcams: true
recordingBasePath: file:///var/kurento
recordingMediaProfile: WEBM_VIDEO_ONLY
recordingFormat: webm
redisExpireTime: 1209600
mcs-path: /mcs
mcs-port: 3010
mcs-address: localhost
mcs-ws-timeout: 30000
freeswitch:
  ip: <ip>
  port: "5066"
  esl_ip: ESL_IP
  esl_port: ESL_PORT
log:
  filename: /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log
  level: verbose
bbb-stream:
  image_name: bbb-stream
  container_type: docker
  bigbluebutton_url: BBBHOST
  bigbluebutton_secret: BBBSECRET
  bot_name: BBBBOTNAME
  bot_join_options:
    userdata-html5autoswaplayout: false
    userdata-html5hidepresentation: false
  k8s:
    namespace: default
    template:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: bbb-stream-
      spec:
        template:
          spec:
            containers:
            - name: bbb-stream-firefox
              image: gcr.io/PROJECT-ID/bbb-stream
              env:
              - name: LINK
                value: ""
              - name: OUTPUT
                value: ""
            restartPolicy: OnFailure
        backoffLimit: 0
processes:
- path: ./lib/mcs-core/process.js
- path: ./lib/screenshare/ScreenshareProcess
- path: ./lib/video/VideoProcess.js
- path: ./lib/audio/AudioProcess.js
media-server-adapters:
- path: kurento/kurento.js
  name: Kurento
- path: freeswitch/freeswitch.js
  name: Freeswitch
conference-media-specs:
  codec_video_main: VP8
  codec_video_content: VP8
  codec_audio: ANY
  H264:
    profile_level_id: 42e01f
    packetization_mode: "0"
    level_asymmetry_allowed: "0"
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
    max_mbps_main: "0"
    max_fs_main: "0"
    max_br_main: "0"
    max_mbps_content: "0"
    max_fs_content: "12288"
    max_br_content: "0"
  VP8:
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
  OPUS:
    useinbandfec: "0"
    maxaveragebitrate: "30000"
    maxplaybackrate: "48000"
    ptime: "20"
    minptime: "10"
    maxptime: "40"
```
