### ISSUE TITLE
Pass customParameter for preferred cameraProfile

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#8293]
`const CAMERA_PROFILES = Meteor.settings.public.kurento.cameraProfiles;`

In settings.yml we have the following structure:

```
    cameraProfiles:
      - id: low
        name: Low quality
        default: false
        bitrate: 100
      - id: medium
        name: Medium quality
        default: true
        bitrate: 200
...
```

We want to support passing of a new custom parameter `userdata-bbb_preferred_camera_profile=low`
so that if the parameter is passed on user join, the `default` option in `cameraProfiles` is ignored and the video preview defaults to the passed preferred option. In case that the camera does not support that profile (or another issue), fallback to the default profile (and keep the existing behavior)
