### ISSUE TITLE
Changes to chatAudioAlerts and chatAudioAlerts in settings.yml not taking effect

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8545]
**Describe the bug**

**To Reproduce**

1.  Edit `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` and change the values for `chatAudioAlerts` and `chatPushAlerts` to `true`

```
defaultSettings:
      application:
        animations: true
        chatAudioAlerts:  true
        chatPushAlerts:  true
        fallbackLocale: en
        overrideLocale: null
```
2. Restart BigBlueButton
3.  Join a session and check the settings options.

**Expected behavior**
The settings for audio/toast messages for new private chat messages should be enabled.

**Actual behavior**
They are still disabled

![image](https://user-images.githubusercontent.com/290351/73123978-c48b5800-3f63-11ea-9f68-92b88d0cab9b.png)

**Comment by capilkey** [comment]
Changing the settings in settings.yml still works. I think what's confusing things is that the values in settings.yml are just defaults and when a user makes a change to the settings in the client they override the defaults. If you join the meeting in a private tab or clear the saved information in your browser the default will be used again. The only way to change it would be to stop persisting setting changes that a user makes, but that has its own drawbacks.

**Comment by aogilvie** [comment]
So in short, there is no way to persist changes to setting.yml ? 
A moderator or even a participant could change the notification settings for all users?

> The only way to change it would be to stop persisting setting changes that a user makes, but that has its own drawbacks.
What about storing the user preferences for notifications in localStorage and always take server side config as default? Is this because there is currently no user configuration system locally yet?

**Comment by capilkey** [comment]
When a user makes a change to their settings it overrides the defaults for them. Users don't affect each other. If they haven't been changed then they use the defaults in settings.yml. I'm not 100% sure where the settings are stored in the browser, but I'm pretty sure it's the local storage.

**Comment by aogilvie** [comment]
Thanks for the clarification. In our case, we ran a fresh RC5 build, changed the following:

```
defaultSettings:
      application:
        animations: true
        chatAudioAlerts: true
        chatPushAlerts: true
        userJoinAudioAlerts: false
        userJoinPushAlerts: false
        fallbackLocale: en
        overrideLocale: null
```

Restarted the html5 client, created a session with greenlight and did not get audio sounds notifications or toast notifications.

Unless the user changes the settings in the html5 client GUI, we cannot get notifications as on by default. I think the server setting changes are not observed. So I think this is a bug.
