### ISSUE TITLE
Big Blue Button wasting a lot of server bandwidth 

### ISSUE THREAD

**Issue by cnx-piyush** [bigbluebutton/bigbluebutton#9007]
**Describe the bug**
WebRTC by design is P2P but in BigBlueButton it seems like server bandwidth is being used even when recording is disabled.

Is there a way to save server bandwidth if user is not doing recording? I have not configured TURN Server.

**To Reproduce**
1. Create a meeting with 1 moderator and 29  attendees
2. Moderator shares a screen and voice 
3. Meeting goes on for 1 hr 
Note : we are using modified version of html5 client(2.2.3) for conference call 

**Expected behavior**
Since bbb is peer to peer we are expecting to have much lower bandwidth usage  . 

**Actual behavior**
We found out that server utilizes for than 6GB of bandwidth 

**Screenshots**
![image](https://user-images.githubusercontent.com/56828575/78669485-f6248600-78f9-11ea-8eea-f0dde7ad2ac3.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version :2.2

The current bandwidth consumption on server is make it expensive for us to host bbb . Let me know if we are doing something wrong

**Comment by capilkey** [comment]
BigBlueButton is definitely not peer-to-peer and most WebRTC implementations that you see these days aren't either. It would be impossible to run a meeting of more than 10 people if the media was P2P and all users were required to send to each other. Sending it to the server allows us to mix the audio streams so everyone only sends and receives one audio stream. It allows the server to take the bandwidth load instead of the individual users for the webcam and screenshare streams.

If BBB were P2P you wouldn't be able to even run the meeting in your example because the presenter would be required to send their screen to each of the 29 viewers. With the default screenshare bitrate you'd be looking at 1.5Mbps (or more) that would have to be sent to each user just for the screenshare.

**Comment by cnx-piyush** [comment]
@capilkey thanks for sharing this valuable information . It is really helpful to understand how screen sharing works in bbb .  

Also could you suggest methods for reducing the server bandwidth ? It will help us a lot .

**Comment by basisbit** [comment]
regarding SFU vs MCU, you might want to read these articles: https://bloggeek.me/webrtc-multiparty-video-alternatives/ and https://www.callstats.io/blog/webrtc-architectures-explained-in-5-minutes-or-less 

To reduce server outbound bandwidth load, these are the usual things you can do:
- ask moderators to not use webcam sharing too much in big meetings (by the way 30 people sharing 1Mb/s webcam stream to 30 participants already hogs 29*30 = 870Mb/s of outbound network bandwidth of the server)
- reduce maximum allowed webcam recording bandwidth
- limit the max amount of participants in a meeting

**Comment by gnaegi** [comment]
You can tweak the video stream settings in this file:  /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Search for** 
```
    cameraProfiles:
    - id: low
      name: Low quality
      default: false
      bitrate: 100
    - id: medium
      name: Medium quality
      default: true
      bitrate: 200
    - id: high
      name: High quality
      default: false
      bitrate: 500
    - id: hd
      name: High definition
      default: false
      bitrate: 800
```
**and replace it with** 

```
    cameraProfiles:
    - id: low
      name: Low quality
      default: true
      bitrate: 80
    - id: medium
      name: Medium quality
      default: false
      bitrate: 150
    - id: high
      name: High quality
      default: false
      bitrate: 350
```

This will 
a) remove the HD bitrate. Nobody really needs this, it is not TV, it's just a web conference!
b) reduce the bitrate for each camera profile (you could even go lower)
c) set the default to the lowest profile with generates moderate video traffic

I do daily meetings with this settings, the traffic load is noch a big issue on the server and the video quality is really still a lot better with the low profile than what you get with many of the commercial tools these days. 

I left the medium and high profile for scenarios where you really need better quality. Most users won't change the quality setting when entering the meeting, so it really is important to se the default to the lowest possible value.
