### ISSUE TITLE
installation ubuntu 14 issue Depends: bbb-webrtc-sfu

### ISSUE THREAD

**Issue by heikle** [bigbluebutton/bigbluebutton#9038]
Hallo,

I try install BigBlueButton on Ubuntu xenial with bbb-install.sh
but i received following error:
 bbb-html5 : Depends: bbb-webrtc-sfu but it is not going to be installed

System is a fresh installed vm with xenial.
I searched this message and found any posts,
but I couldn't find a solution.

I made some attempts and found a problem with:
install libgstreamer-plugins-bad1.5-0 andor libwayland-client0 
(see below)

what am I doing wrong?

regards Heiko

-----------------------------------------
details:
```

# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v
xenial-220

``````

...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-webrtc-sfu but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```


# apt-cache policy bbb-html5
bbb-html5:
  Installed: (none)
  Candidate: 1:2.2.0-870
  Version table:
     1:2.2.0-870 500
        500 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 Packages



# apt-cache show bbb-html5 bbb-webrtc-sfu | egrep -i "Package|Depends|hold"
Package: bbb-html5
Depends: bbb-webrtc-sfu,bbb-apps-video-broadcast,yq,bbb-etherpad
Package: bbb-webrtc-sfu
Depends: git-core,nginx,kurento-media-server,openh264-gst-plugins-bad-1.5,bbb-apps-akka,bbb-transcode-akka,nodejs,npm,build-essential,yq,xmlstarlet



```

```

# apt-get -o Debug::pkgProblemResolver=yes install  bigbluebutton
...
Starting pkgProblemResolver with broken count: 2
Starting 2 pkgProblemResolver with broken count: 2
Investigating (0) openh264-gst-plugins-bad-1.5 [ amd64 ] < none -> 1.8.1-1kurento4.16.04 > ( libs )
Broken openh264-gst-plugins-bad-1.5:amd64 Depends on libgstreamer-plugins-bad1.5-0 [ amd64 ] < none -> 1.8.1-1kurento4.16.04 > ( libs ) (= 1.8.1-1k
urento4.16.04)
  Considering libgstreamer-plugins-bad1.5-0:amd64 0 as a solution to openh264-gst-plugins-bad-1.5:amd64 1
  Holding Back openh264-gst-plugins-bad-1.5:amd64 rather than change libgstreamer-plugins-bad1.5-0:amd64
Investigating (0) kms-elements [ amd64 ] < none -> 6.13.0.xenial~20200323124530.47.cc7e5c4 > ( libs )
Broken kms-elements:amd64 Depends on openh264-gst-plugins-bad-1.5 [ amd64 ] < none -> 1.8.1-1kurento4.16.04 > ( libs )
  Considering openh264-gst-plugins-bad-1.5:amd64 1 as a solution to kms-elements:amd64 1
  Holding Back kms-elements:amd64 rather than change openh264-gst-plugins-bad-1.5:amd64
...
    Reinst Failed early because of libwayland-client0:amd64
    Reinst Failed because of libgstreamer-plugins-bad1.5-0:amd64
    Reinst Failed because of gstreamer1.5-plugins-bad:amd64
    Reinst Failed because of kurento-media-server:amd64
    Reinst Failed because of bbb-webrtc-sfu:amd64
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


   - libwayland-client0 ???



```

```

- test18

# apt-get update
# apt-get install libgstreamer-plugins-bad1.5-0
...
The following packages have unmet dependencies:
 libgstreamer-plugins-bad1.5-0 : Depends: libwayland-client0 (>= 1.9.91) but 1.9.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.





- test 19
# apt-get install libwayland-client0
...



- test20
#  apt-get install libgstreamer-plugins-bad1.5-0
...
The following packages have unmet dependencies:
 libgstreamer-plugins-bad1.5-0 : Depends: libwayland-client0 (>= 1.9.91) but 1.9.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.

    - exact the same error before installed libwayland-client0


- test21
# apt-cache policy libgstreamer-plugins-bad1.5-0 libwayland-client0
libgstreamer-plugins-bad1.5-0:
  Installed: (none)
  Candidate: 1.8.1-1kurento4.16.04
  Version table:
     1.8.1-1kurento4.16.04 500
        500 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 Packages
libwayland-client0:
  Installed: 1.9.0-1
  Candidate: 1.9.0-1
  Version table:
 *** 1.9.0-1 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status


```

```
