### ISSUE TITLE
Add new browser to supported list?

### ISSUE THREAD

**Issue by nguyendinhdoan** [bigbluebutton/bigbluebutton#9091]
**Describe the bug**
I got unsupported browser issue with this browser: https://coccoc.com
Here is my config:
`/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`
```
minBrowserVersions:
  - browser: chrome
    version: 59
  - browser: chromeMobileIOS
    version: Infinity
  - browser: firefox
    version: 52
  - browser: firefoxMobile
    version: 52
  - browser: edge
    version: 17
  - browser: ie
    version: Infinity
  - browser: safari
    version: [11, 1]
  - browser: mobileSafari
    version: [11, 1]
  - browser: opera
    version: 46
  - browser: electron
    version: [0, 36]
  - browser: coc_coc_browser
    version: 60
```

The user-agent is:
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/86.0.166 Chrome/80.0.3987.166 Safari/537.36`

Then I ran: `bbb-conf --restart`
Then I tried joining a room
Then it showed the issue saying unsupported browser: http://prntscr.com/rzqr5v

I also restarted greenlight but no help.
Can it due to the symbols in the browser name? coc_coc_browser

**To Reproduce**
1. Install coccoc browser https://coccoc.com/
2. Try joining a meeting
