### ISSUE TITLE
Default personal room created even if user role has not privilege to create rooms

### ISSUE THREAD

**Issue by wociscz** [bigbluebutton/bigbluebutton#9172]
When I have disabled room creation for user role (for default user role), default personal room is created upon user first login. Room list is populated with Default rooms (for users which are allowed to manage rooms) and this make mess to manage rooms. This rooms can't be used by default users at all, because default users can't see them.

**To Reproduce**
1. Edit default user role and disable room creation
2. Register new user
3. Login new user
4. Default personal room for this particular user is created and not visible for him
5. Default personal rooms are visible for users with permission to manage rooms

**Expected behavior**
Do not create default personal room for users not allowed to (by their user role).

Don't know if this is bug/or rather feature request - just can't find any configuration option to stop this behavior - I expect, that if role is not allowed to create rooms even default private room can't be created.

```
BigBlueButton Server 2.2.5 (1848)
                    Kernel version: 4.4.0-176-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 7980 MB
                         CPU cores: 2

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.domain.tld
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.domain.tld
                              port: 
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.domain.tld
                              red5: bbb.domain.tld
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: x.x.x.x
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: x.x.x.x:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.domain.tld
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: x.x.x.x

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: x.x.x.x
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: x.x.x.x
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 874
                        kurentoUrl: wss://bbb.domain.tld/bbb-webrtc-sfu
                  enableListenOnly: true
```
